namespace DiscordSysInfoRPC;

public static class Loc
{
    private static readonly Dictionary<string, (string Ru, string En)> Strings = new()
    {
        ["AppTitle"] = ("Discord SysInfo RPC", "Discord SysInfo RPC"),
        ["StatusDisconnected"] = ("Отключено", "Disconnected"),
        ["StatusConnected"] = ("Подключено", "Connected"),
        ["StatusNoAccess"] = ("Нет доступа", "No access"),
        ["SectionSettings"] = ("НАСТРОЙКИ", "SETTINGS"),
        ["SectionAdditional"] = ("ДОПОЛНИТЕЛЬНО", "ADDITIONAL"),
        ["SectionSystem"] = ("СИСТЕМА", "SYSTEM"),
        ["System"] = ("СИСТЕМА ▼", "SYSTEM ▼"),
        ["SystemExpanded"] = ("СИСТЕМА ▲", "SYSTEM ▲"),
        ["LabelAppId"] = ("Application ID", "Application ID"),
        ["PlaceholderAppId"] = ("Введите Application ID", "Enter your Application ID"),
        ["PlaceholderActivityName"] = ("Название (пусто — из портала)", "Name (empty — from portal)"),
        ["PlaceholderButtonLabel"] = ("Текст кнопки", "Button label"),
        ["PlaceholderButtonUrl"] = ("https://...", "https://..."),
        ["LabelActivityName"] = ("Название активности", "Activity name"),
        ["LabelActivityType"] = ("Тип активности", "Activity type"),
        ["LabelImageSet"] = ("Набор картинок", "Image set"),
        ["LabelTimerMode"] = ("Режим таймера", "Timer mode"),
        ["LabelWatchingDuration"] = ("Режим времени", "Time mode"),
        ["WatchProgressBar"] = ("Полоска прогресса", "Progress bar"),
        ["LabelWatchingCustomDuration"] = ("Длительность просмотра", "Watch duration"),
        ["WatchingDurationHint"] = ("Укажите длительность видео или стрима (от 1 мин. до 24 ч.)", "Set video or stream duration (from 1 min up to 24 h)"),
        ["UnitHours"] = ("ч", "h"),
        ["UnitMinutes"] = ("мин", "min"),
        ["WatchDuration30"] = ("30 мин", "30 min"),
        ["WatchDuration45"] = ("45 мин", "45 min"),
        ["WatchDuration60"] = ("60 мин", "60 min"),
        ["WatchDuration90"] = ("90 мин", "90 min"),
        ["WatchDuration120"] = ("2 ч", "2 h"),
        ["WatchDuration180"] = ("3 ч", "3 h"),
        ["LabelUpdateInterval"] = ("Интервал смены / обновления", "Rotation / update interval"),
        ["LabelLanguage"] = ("Язык интерфейса", "Interface language"),
        ["AutoConnect"] = ("Автоподключение", "Auto-connect"),
        ["DetectForegroundApp"] = ("Подхватывать запущенное окно", "Detect focused window"),
        ["DetectForegroundAppHint"] = ("Название и иконка берутся из активной программы, статы ПК остаются", "Uses the focused app name and icon; PC stats stay in the status"),
        ["UseShortcutName"] = ("Название из ярлыка", "Use shortcut name"),
        ["UseShortcutNameHint"] = ("Если у exe нет нормального имени — взять имя ярлыка с рабочего стола или из меню Пуск", "If the exe has no real name, use the Desktop or Start Menu shortcut name"),
        ["CustomStatusText"] = ("Свой текст в статусе", "Custom status text"),
        ["CustomStatusTextHint"] = ("Заменяет шкалу нагрузки и данные ПК на ваш собственный текст", "Replaces the load bar and PC specs with your own custom text"),
        ["LabelCustomDetails"] = ("Верхняя строка (Детали)", "Upper line (Details)"),
        ["PlaceholderCustomDetails"] = ("Например: Играет соло / В лобби (или пусто)", "e.g. Playing solo / In lobby (or empty)"),
        ["LabelCustomState"] = ("Нижняя строка (Состояние)", "Lower line (State)"),
        ["PlaceholderCustomState"] = ("Например: Глава 3 / Ранг: Алмаз (или пусто)", "e.g. Chapter 3 / Rank: Diamond (or empty)"),
        ["CustomStatusTagsHint"] = ("Оставьте поле пустым, чтобы скрыть строку. Поддерживаются теги: {cpu}, {gpu}, {ram}, {cpu_temp}, {gpu_temp}", "Leave empty to hide line. Supported tags: {cpu}, {gpu}, {ram}, {cpu_temp}, {gpu_temp}"),
        ["ShowPromoButton"] = ("Кнопка «✨ Хочу такой же» в Discord", "«✨ Get this RPC» button in Discord"),
        ["ShowPromoButtonHint"] = ("Поддержите разработчика и расскажите друзьям, где взять такой софт. Кнопка ведёт на disflare.com", "Support the developer and show friends where to get this software. Links to disflare.com"),
        ["PromoButtonLabel"] = ("✨ Хочу такой же", "✨ Get this RPC"),
        ["ShowButton"] = ("Показывать свою кнопку", "Show custom button"),
        ["LabelButtonText"] = ("Текст кнопки", "Button label"),
        ["LabelButtonUrl"] = ("URL кнопки", "Button URL"),
        ["ActivityPlaying"] = ("Играет (Playing)", "Playing"),
        ["ActivityListening"] = ("Слушает (Listening)", "Listening"),
        ["ActivityWatching"] = ("Смотрит (Watching)", "Watching"),
        ["ActivityCompeting"] = ("Соревнуется (Competing)", "Competing"),
        ["ImageKiara"] = ("Kiara", "Kiara"),
        ["ImageGura"] = ("Gura", "Gura"),
        ["ImageMori"] = ("Mori", "Mori"),
        ["ImageCustom"] = ("Свой набор", "Custom set"),
        ["ImageDiscordLabel"] = ("Discord Label", "Discord Label"),
        ["TimerElapsed"] = ("С момента запуска", "Since launch"),
        ["TimerStartOfDay"] = ("С начала дня", "Since start of day"),
        ["Interval5"] = ("5 сек", "5 sec"),
        ["Interval10"] = ("10 сек", "10 sec"),
        ["Interval15"] = ("15 сек", "15 sec"),
        ["Interval30"] = ("30 сек", "30 sec"),
        ["LangRu"] = ("Русский", "Russian"),
        ["LangEn"] = ("English", "English"),
        ["Help"] = ("Помощь ▼", "Help ▼"),
        ["HelpExpanded"] = ("Помощь ▲", "Help ▲"),
        ["HelpDevPortalTitle"] = ("Создание Discord Application", "Creating a Discord Application"),
        ["HelpDevPortal1"] = ("1. Перейдите на Discord Developer Portal", "1. Go to the Discord Developer Portal"),
        ["HelpDevPortal2"] = ("2. Нажмите \"New Application\"", "2. Click \"New Application\""),
        ["HelpDevPortal3"] = ("3. Скопируйте Application ID", "3. Copy the Application ID"),
        ["HelpDevPortalLink"] = ("Открыть Developer Portal →", "Open Developer Portal →"),
        ["HelpServerTitle"] = ("Официальный сайт", "Official Website"),
        ["HelpServerHint"] = ("Новости, обновления и документация проекта доступны на нашем сайте.", "News, updates, and documentation are available on our website."),
        ["HelpServerLink"] = ("Перейти на сайт →", "Visit website →"),
        ["HelpInfoTitle"] = ("Информация", "Information"),
        ["CopyId"] = ("Копировать", "Copy"),
        ["Disconnect"] = ("Отключить", "Disconnect"),
        ["Connect"] = ("Подключить", "Connect"),
        ["Save"] = ("Сохранить", "Save"),
        ["Saved"] = ("✓ Сохранено", "✓ Saved"),
        ["Connecting"] = ("...", "..."),
        ["FooterPrefix"] = ("С Любовью к Discord ", "Made with love for Discord "),
        ["Cpu"] = ("CPU:", "CPU:"),
        ["CpuLoad"] = ("CPU Load:", "CPU Load:"),
        ["CpuTemp"] = ("CPU Temp:", "CPU Temp:"),
        ["Gpu"] = ("GPU:", "GPU:"),
        ["GpuLoad"] = ("GPU Load:", "GPU Load:"),
        ["GpuTemp"] = ("GPU Temp:", "GPU Temp:"),
        ["Ram"] = ("RAM:", "RAM:"),
        ["RamUsed"] = ("RAM Used:", "RAM Used:"),
        ["TrayOpen"] = ("Открыть", "Open"),
        ["TrayExit"] = ("Выход", "Exit"),
        ["InitErrorTitle"] = ("Предупреждение", "Warning"),
        ["InitError"] = ("Ошибка инициализации: {0}", "Initialization error: {0}"),
        ["BlockedTitle"] = ("Доступ заблокирован", "Access blocked"),
        ["NoAccessTitle"] = ("Нет доступа", "No access"),
        ["NoAccessDefault"] = ("Доступ не предоставлен.\n\nСкопируйте ваш ID и отправьте разработчику.", "Access not granted.\n\nCopy your ID and send it to the developer."),
        ["NoAccessShort"] = ("Доступ не предоставлен.", "Access not granted."),
        ["IdCopiedTitle"] = ("Скопировано", "Copied"),
        ["IdCopied"] = ("ID скопирован:\n{0}", "ID copied:\n{0}"),
        ["SettingsTitle"] = ("Расширенные настройки", "Advanced settings"),
        ["SettingsCustomImages"] = ("Кастомные изображения", "Custom images"),
        ["SettingsCustomHint"] = ("Оставьте пустым для использования стандартных", "Leave empty to use default sets"),
        ["SettingsIdle"] = ("Idle (низкая нагрузка)", "Idle (low load)"),
        ["SettingsLow"] = ("Low (средняя нагрузка)", "Low (medium load)"),
        ["SettingsMedium"] = ("Medium (высокая нагрузка)", "Medium (high load)"),
        ["SettingsHigh"] = ("High (очень высокая)", "High (very high)"),
        ["SettingsThresholds"] = ("Пороги нагрузки (%)", "Load thresholds (%)"),
        ["SettingsThresholdsHint"] = ("При какой нагрузке менять изображение", "When to switch images by load"),
        ["SettingsThresholdLegend"] = ("Idle: 0% — Low%, Low: Low% — Medium%, Medium: Medium% — High%, High: High%+",
            "Idle: 0% — Low%, Low: Low% — Medium%, Medium: Medium% — High%, High: High%+"),
        ["Reset"] = ("Сбросить", "Reset"),
    };

    public static string Language { get; private set; } = "ru";

    public static void SetLanguage(string lang)
    {
        Language = lang.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en" : "ru";
    }

    public static string Get(string key)
    {
        if (!Strings.TryGetValue(key, out var pair))
            return key;
        return Language == "en" ? pair.En : pair.Ru;
    }

    public static string Format(string key, params object[] args) =>
        string.Format(Get(key), args);
}
